### ISSUE TITLE
HUAWEI(GRA-UL00) pub or sub with h264 lead crash

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-android#147]
1: huawei join room
2: huawei publish local stream with h264 or sub mix stream with h264

log:
01-04 09:55:11.619 10652-10884/owt.sample.conference E/AndroidRuntime: FATAL EXCEPTION: pool-11-thread-1
    Process: owt.sample.conference, PID: 10652
    java.lang.NullPointerException: Attempt to invoke virtual method 'void owt.conference.Subscription.onError(owt.base.OwtError)' on a null object reference
        at owt.conference.ConferenceClient.onError(ConferenceClient.java:895)
        at owt.conference.ConferencePeerConnectionChannel.lambda$onSetFailure$23$ConferencePeerConnectionChannel(ConferencePeerConnectionChannel.java:118)
        at owt.conference.-$$Lambda$ConferencePeerConnectionChannel$SuZqmJsooiK8I2_SjeocaJFNI2E.run(lambda)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:831)

**Comment by zhangyihui1** [comment]
mcu : Release-v20190829ubuntu.tgz

**Comment by zhangyihui1** [comment]
fix in https://github.com/open-webrtc-toolkit/owt-deps-webrtc/pull/37
