### ISSUE TITLE
Meizu(PRO 7-S)  pub or sub with videoCodec h264 lead crash

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-android#169]
1: meizu device join room
2: meizu device subscribe mix stream with h264

mcu : Release-v20190922 (ubuntu hardware)
carsh log:
2019-09-27 14:42:41.923 6380-6721/? E/AndroidRuntime: FATAL EXCEPTION: pool-8-thread-1
    Process: owt.sample.conference, PID: 6380
    java.lang.NullPointerException: Attempt to invoke virtual method 'void owt.conference.Subscription.onError(owt.base.OwtError)' on a null object reference
        at owt.conference.ConferenceClient.onError(ConferenceClient.java:895)
        at owt.conference.ConferencePeerConnectionChannel.lambda$onSetFailure$23$ConferencePeerConnectionChannel(ConferencePeerConnectionChannel.java:118)
        at owt.conference.-$$Lambda$ConferencePeerConnectionChannel$SuZqmJsooiK8I2_SjeocaJFNI2E.run(lambda)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by zhangyihui1** [comment]
fix in https://github.com/open-webrtc-toolkit/owt-deps-webrtc/pull/37
