### ISSUE TITLE
Android SDK will crash if subscribe simulcast stream with h264-B video codec

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-android#171]
1: chrome and android join room
2: chrome publish simulcast stream with resolution (640*360)
options = {
				audio : true,
				video : [
	                                {rid: 'f', active: true, scaleResolutionDownBy: 4.0},
					{rid: 'q', active: true, scaleResolutionDownBy: 2.0},
					{rid: 'h', active: true, scaleResolutionDownBy: 1.0},
				]
		}
3: android subscribe this simulcast stream with set correct rid

env:
android device: opop R17
mcu version: release-v20191009

log:
2019-10-10 10:27:13.951 13631-13702/owt.sample.conference E/OWT_CONF: Failed to subscribe Failed to set remote answer sdp: Failed to set remote video description send parameters.
    
    --------- beginning of crash
2019-10-10 10:27:13.954 13631-13726/owt.sample.conference E/AndroidRuntime: FATAL EXCEPTION: pool-6-thread-1
    Process: owt.sample.conference, PID: 13631
    java.lang.NullPointerException: Attempt to invoke virtual method 'void owt.conference.Subscription.onError(owt.base.OwtError)' on a null object reference
        at owt.conference.ConferenceClient.onError(ConferenceClient.java:895)
        at owt.conference.ConferencePeerConnectionChannel.lambda$onSetFailure$23$ConferencePeerConnectionChannel(ConferencePeerConnectionChannel.java:118)
        at owt.conference.-$$Lambda$ConferencePeerConnectionChannel$SuZqmJsooiK8I2_SjeocaJFNI2E.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by zhangyihui1** [comment]
verify in Release-v20191017encrypt
