### ISSUE TITLE
EncoderQueue - (9464)  Crash

### ISSUE THREAD

**Issue by JustinWjq** [open-webrtc-toolkit/owt-client-android#215]
05-07 11:37:49.982 8712 9568 W OMXUtils: do not know color format 0x7fa30c04 = 2141391876
--
15305-07 11:37:49.983 8712 9568 W OMXUtils: do not know color format 0x7f000789 = 2130708361
15405-07 11:37:49.989 8712 9568 E ACodec : [OMX.qcom.video.encoder.vp8] failed to set input port definition parameters.
15505-07 11:37:49.989 8712 9568 E ACodec : [OMX.qcom.video.encoder.vp8] configureCodec returning error -1010
15605-07 11:37:49.989 8712 9568 E ACodec : signalError(omxError 0x80001001, internalError -1010)
15705-07 11:37:49.991 8712 9567 E MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
15805-07 11:37:49.992 8712 9464 E MediaCodec: configure failed with err 0xfffffc0e, resetting...
15905-07 11:37:50.000 8712 9568 I OMXClient: Treble IOmx obtained
16005-07 11:37:50.014 8712 9568 I ACodec : In onAllocateComponent create compenent, codec name: OMX.qcom.video.encoder.vp8
16105-07 11:37:50.016 8712 9464 E org.webrtc.Logging: MediaCodecVideoEncoder: initEncode failed
16205-07 11:37:50.016 8712 9464 E org.webrtc.Logging: MediaCodecVideoEncoder: android.media.MediaCodec$CodecException: Error 0xfffffc0e
16305-07 11:37:50.017 8712 9464 W System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension;
16405-07 11:37:50.017 8712 9464 W System.err: at org.webrtc.Logging.getStackTraceString(Logging.java:176)
16505-07 11:37:50.017 8712 9464 W System.err: at org.webrtc.Logging.e(Logging.java:156)
16605-07 11:37:50.017 8712 9464 W System.err: at org.webrtc.MediaCodecVideoEncoder.initEncode(MediaCodecVideoEncoder.java:587)

**Comment by JustinWjq** [comment]
ROM  HuaWei/EMOTION  
设备机型  华为 DUB AL00 
系统版本 Android 8.1.0,level 27
Mcu版本 4.1 （android sdk ）

**Comment by JustinWjq** [comment]
场景应该是localstream 在降低分辨率，然后初始化Encoder报错了，具体原因我就不太清楚了，有部分机型在bugly上面基本都是这个报错，麻烦有空的话，可以帮我分析一下嘛，这个对于我们公司部分留存很重要，谢谢了。
