### ISSUE TITLE
MediaCodecVideoEncoder: initEncode failed

### ISSUE THREAD

**Issue by JustinWjq** [open-webrtc-toolkit/owt-client-android#216]
Android 8.1.0,level 27  
  vivo/FUNTOUCH

**Comment by JustinWjq** [comment]
error msg：


[OMX.qcom.video.encoder.vp8]configureCodec AMessage(what = 'conf', target = 118) = {
--
18305-26 10:26:39.098 28376 5292 I ACodec : int32_t color-format = 21
18405-26 10:26:39.098 28376 5292 I ACodec : int32_t i-frame-interval = 100
18505-26 10:26:39.098 28376 5292 I ACodec : string mime = "video/x-vnd.on2.vp8"
18605-26 10:26:39.098 28376 5292 I ACodec : int32_t width = 270
18705-26 10:26:39.098 28376 5292 I ACodec : int32_t bitrate-mode = 2
18805-26 10:26:39.098 28376 5292 I ACodec : int32_t bitrate = 139000
18905-26 10:26:39.098 28376 5292 I ACodec : int32_t frame-rate = 30
19005-26 10:26:39.098 28376 5292 I ACodec : int32_t height = 480
19105-26 10:26:39.098 28376 5292 I ACodec : int32_t encoder = 1
19205-26 10:26:39.098 28376 5292 I ACodec : }
19305-26 10:26:39.100 28376 5292 I ExtendedACodec: setupVideoEncoder()
19405-26 10:26:39.101 28376 5292 W OMXUtils: do not know color format 0x7fa30c04 = 2141391876
19505-26 10:26:39.102 28376 5292 W OMXUtils: do not know color format 0x7f000789 = 2130708361
19605-26 10:26:39.118 28376 5292 E ACodec : [OMX.qcom.video.encoder.vp8] failed to set output port definition parameters.
19705-26 10:26:39.118 28376 5292 W ExtendedACodec: Failed to get extension for extradata parameter
19805-26 10:26:39.118 28376 5292 E ACodec : [OMX.qcom.video.encoder.vp8] configureCodec returning error -1010
19905-26 10:26:39.118 28376 5292 E ACodec : signalError(omxError 0x80001001, internalError -1010)
20005-26 10:26:39.118 28376 5291 E MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
20105-26 10:26:39.120 28376 438 E MediaCodec: configure failed with err 0xfffffc0e, resetting...

05-26 10:26:39.120 28376 438 I MediaCodec: reset
--
20305-26 10:26:39.120 28376 438 I MediaCodec: release
20405-26 10:26:39.120 28376 5291 I MediaCodec: kWhatStop or kWhatRelease
20505-26 10:26:39.120 28376 5291 I ACodec : initiateShutdown kWhatReleaseCodecInstance
20605-26 10:26:39.125 28376 438 I ACodec : mIsVivoLogEnable = 0
20705-26 10:26:39.143 28376 438 E org.webrtc.Logging: MediaCodecVideoEncoder: initEncode failed
20805-26 10:26:39.144 28376 438 E org.webrtc.Logging: MediaCodecVideoEncoder: android.media.MediaCodec$CodecException: Error 0xfffffc0e
05-26 10:26:39.157 28376 438 W System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension;
--
21005-26 10:26:39.167 28376 438 W System.err: at org.webrtc.Logging.getStackTraceString(Logging.java:176)
21105-26 10:26:39.167 28376 438 W System.err: at org.webrtc.Logging.e(Logging.java:156)
21205-26 10:26:39.167 28376 438 W System.err: at org.webrtc.MediaCodecVideoEncoder.initEncode(MediaCodecVideoEncoder.java:587)

**Comment by JustinWjq** [comment]
error msg：

[OMX.qcom.video.encoder.vp8]configureCodec AMessage(what = 'conf', target = 118) = {
18305-26 10:26:39.098 28376 5292 I ACodec : int32_t color-format = 21
18405-26 10:26:39.098 28376 5292 I ACodec : int32_t i-frame-interval = 100
18505-26 10:26:39.098 28376 5292 I ACodec : string mime = "video/x-vnd.on2.vp8"
18605-26 10:26:39.098 28376 5292 I ACodec : int32_t width = 270
18705-26 10:26:39.098 28376 5292 I ACodec : int32_t bitrate-mode = 2
18805-26 10:26:39.098 28376 5292 I ACodec : int32_t bitrate = 139000
18905-26 10:26:39.098 28376 5292 I ACodec : int32_t frame-rate = 30
19005-26 10:26:39.098 28376 5292 I ACodec : int32_t height = 480
19105-26 10:26:39.098 28376 5292 I ACodec : int32_t encoder = 1
19205-26 10:26:39.098 28376 5292 I ACodec : }
19305-26 10:26:39.100 28376 5292 I ExtendedACodec: setupVideoEncoder()
19405-26 10:26:39.101 28376 5292 W OMXUtils: do not know color format 0x7fa30c04 = 2141391876
19505-26 10:26:39.102 28376 5292 W OMXUtils: do not know color format 0x7f000789 = 2130708361
19605-26 10:26:39.118 28376 5292 E ACodec : [OMX.qcom.video.encoder.vp8] failed to set output port definition parameters.
19705-26 10:26:39.118 28376 5292 W ExtendedACodec: Failed to get extension for extradata parameter
19805-26 10:26:39.118 28376 5292 E ACodec : [OMX.qcom.video.encoder.vp8] configureCodec returning error -1010
19905-26 10:26:39.118 28376 5292 E ACodec : signalError(omxError 0x80001001, internalError -1010)
20005-26 10:26:39.118 28376 5291 E MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
20105-26 10:26:39.120 28376 438 E MediaCodec: configure failed with err 0xfffffc0e, resetting...

05-26 10:26:39.120 28376 438 I MediaCodec: reset
20305-26 10:26:39.120 28376 438 I MediaCodec: release
20405-26 10:26:39.120 28376 5291 I MediaCodec: kWhatStop or kWhatRelease
20505-26 10:26:39.120 28376 5291 I ACodec : initiateShutdown kWhatReleaseCodecInstance
20605-26 10:26:39.125 28376 438 I ACodec : mIsVivoLogEnable = 0
20705-26 10:26:39.143 28376 438 E org.webrtc.Logging: MediaCodecVideoEncoder: initEncode failed
20805-26 10:26:39.144 28376 438 E org.webrtc.Logging: MediaCodecVideoEncoder: android.media.MediaCodec$CodecException: Error 0xfffffc0e
05-26 10:26:39.157 28376 438 W System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/devtools/build/android/desugar/runtime/ThrowableExtension;
21005-26 10:26:39.167 28376 438 W System.err: at org.webrtc.Logging.getStackTraceString(Logging.java:176)
21105-26 10:26:39.167 28376 438 W System.err: at org.webrtc.Logging.e(Logging.java:156)
21205-26 10:26:39.167 28376 438 W System.err: at org.webrtc.MediaCodecVideoEncoder.initEncode(MediaCodecVideoEncoder.java:587)
