### ISSUE TITLE
java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003

### ISSUE THREAD

**Issue by tenchong** [open-webrtc-toolkit/owt-client-android#261]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.miaohuida.tcmeeting, PID: 15117
    java.lang.RuntimeException: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:282)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:78)
        at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:215)
        at org.webrtc.EglBase$-CC.create(EglBase.java:158)
        at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:241)
        at org.webrtc.-$$Lambda$EglRenderer$A5MPsBufyTiKpmjvPS46Dr9iaHs.run(Unknown Source:6)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
        at android.os.Looper.loop(Looper.java:227)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
        at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:196)
        at org.webrtc.EglRenderer.init(EglRenderer.java:232)
        at org.webrtc.EglRenderer.init(EglRenderer.java:259)
        at org.webrtc.SurfaceEglRenderer.init(SurfaceEglRenderer.java:61)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:87)
        at org.webrtc.SurfaceViewRenderer.init(SurfaceViewRenderer.java:71)
        at com.mhd.core.fragment.WriteABoothFragment.init(WriteABoothFragment.java:95)
        at com.mhd.core.bsae.BaseFragment.onViewCreated(BaseFragment.java:79)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:892)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:434)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:227)
        at android.app.ActivityThread.main(ActivityThread.java:7573)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
     Caused by: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:282)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:78)
        at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:215)
        at org.webrtc.EglBase$-CC.create(EglBase.java:158)
        at org.webrtc.EglRenderer.lambda$init$0$EglRenderer(EglRenderer.java:241)
        at org.webrtc.-$$Lambda$EglRenderer$A5MPsBufyTiKpmjvPS46Dr9iaHs.run(Unknown Source:6)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:199)
        at org.webrtc.ThreadUtils$4.call(ThreadUtils.java:196)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at org.webrtc.EglRenderer$HandlerWithExceptionCallback.dispatchMessage(EglRenderer.java:103)
        at android.os.Looper.loop(Looper.java:227)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by 779594494** [comment]
2021-09-18 14:09:11.570 1258-30714/? E/OMXNodeInstance: getParameter(0xef5fc244:qcom.decoder.vp8, ??(0x7f000046)) ERROR: UnsupportedIndex(0x8000101a)
2021-09-18 14:09:11.570 17298-20121/? E/org.webrtc.Logging: SurfaceTextureHelper: decoder-texture-thread create failure
2021-09-18 14:09:11.570 1258-30714/? E/OMX-VDEC-1080P: set_parameter: Error: 0x80001019, setting param 0x7f00005d
2021-09-18 14:09:11.570 1258-30714/? E/OMXNodeInstance: setParameter(0xef5fc244:qcom.decoder.vp8, OMX.google.android.index.allocateNativeHandle(0x7f00005d): Output:1 en=0) ERROR: UnsupportedSetting(0x80001019)
2021-09-18 14:09:11.570 17298-20121/? E/org.webrtc.Logging: SurfaceTextureHelper: java.lang.RuntimeException: Failed to create EGL context: 0x3003
2021-09-18 14:09:11.570 1258-30714/? E/OMX-VDEC-1080P: Extension: OMX.google.android.index.storeANWBufferInMetadata not implemented
2021-09-18 14:09:11.571 17298-20121/? E/org.webrtc.Logging: SurfaceTextureHelper: java.lang.RuntimeException: Failed to create EGL context: 0x3003
        at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:282)
        at org.webrtc.EglBase14Impl.<init>(EglBase14Impl.java:78)
        at org.webrtc.EglBase$-CC.createEgl14(EglBase.java:215)
        at org.webrtc.EglBase$-CC.create(EglBase.java:158)
        at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:187)
        at org.webrtc.SurfaceTextureHelper.<init>(SurfaceTextureHelper.java:33)
        at org.webrtc.SurfaceTextureHelper$1.call(SurfaceTextureHelper.java:75)
        at org.webrtc.SurfaceTextureHelper$1.call(SurfaceTextureHelper.java:70)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:236)
        at android.os.HandlerThread.run(HandlerThread.java:67)
2021-09-18 14:09:11.571 17298-20026/? E/rtc: #
    # Fatal error in: gen/third_party/webrtc/sdk/android/generated_metrics_jni/../../../../../../../../third_party/webrtc/sdk/android/src/jni/jni_generator_helper.h, line 94
    # last system error: 0
    # Check failed: !env->ExceptionCheck()
    #
