### ISSUE TITLE
Since 5.0 screen capturer crashes in onFrame

### ISSUE THREAD

**Issue by dilldilldill** [open-webrtc-toolkit/owt-client-android#269]
```
W/System.err: java.lang.IllegalStateException: release() called on an object with refcount < 1
W/System.err:     at org.webrtc.RefCountDelegate.release(RefCountDelegate.java:42)
W/System.err:     at org.webrtc.TextureBufferImpl.release(TextureBufferImpl.java:125)
W/System.err:     at org.webrtc.VideoFrame.release(VideoFrame.java:188)
W/System.err:     at org.webrtc.VideoSource$1.onFrameCaptured(VideoSource.java:77)
W/System.err:     at org.webrtc.ScreenCapturerAndroid.onFrame(ScreenCapturerAndroid.java:200)
W/System.err:     at org.webrtc.SurfaceTextureHelper.tryDeliverTextureFrame(SurfaceTextureHelper.java:374)
W/System.err:     at org.webrtc.SurfaceTextureHelper.lambda$new$0$SurfaceTextureHelper(SurfaceTextureHelper.java:207)
W/System.err:     at org.webrtc.-$$Lambda$SurfaceTextureHelper$073Iq_oVBecUTQR2U0VmYQ8_7lM.onFrameAvailable(Unknown Source:2)
W/System.err:     at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:211)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loop(Looper.java:233)
W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:67
```

As I updated my the OWT android client to the newest 5.0 release the very simple [OwtScreenCapturer](https://github.com/open-webrtc-toolkit/owt-client-android/blob/f2294c55f9d3bdc1de78ab84c9b7d018c3e3a04b/src/sample/utils/src/main/java/owt/sample/utils/OwtScreenCapturer.java) fails with the above IllegalStateException. As the code I am using seems trivial and this problem was introduced when I updated OWT to 5.0 I tend to believe, that the problem is somewhere in the SurfaceTextureHelper maybe? I tried to look into the code but couldn't find anything obvious. The fact that I can not find any one on the internet having the same problem leaves me a little unconfident. Any ideas any one?

**Comment by PonyHugger** [comment]
Same here! Did you solve it yet?

**Comment by dilldilldill** [comment]
> Same here! Did you solve it yet?

Unfotunately not.

**Comment by PonyHugger** [comment]
That's sad. It is a big blocker for us.
@jianjunz @zhangyihui1 do you guys have an idea?

**Comment by PonyHugger** [comment]
@dilldilldill did you find a solution? Unfortunately, the owt people don't care...

**Comment by dilldilldill** [comment]
> @dilldilldill did you find a solution? Unfortunately, the owt people don't care...

Not yet, still checking the repo daily, waiting for a fix

**Comment by PonyHugger** [comment]
nope... not fixed yet... weird issue, no support... :(
