### ISSUE TITLE
[Conference] Native crash during repeatedly publishing and stopping

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-android#32]
1: user1 join room
2: user1 publish local stream
3: user1 publication.stop()

repeat step 2 and step 3 for few times
[publishStability.log](https://github.com/open-media-streamer/oms-client-android/files/2583878/publishStability.log)

> 11-15 14:16:18.331 4396-4440/oms.test.conference.apitest W/System.err: java.util.ConcurrentModificationException
> 11-15 14:16:18.331 4396-4440/oms.test.conference.apitest W/System.err:     at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
> 11-15 14:16:18.331 4396-4440/oms.test.conference.apitest W/System.err:     at oms.conference.ConferencePeerConnectionChannel.onSetSuccess(ConferencePeerConnectionChannel.java:103)
> 11-15 14:16:18.331 4396-4440/oms.test.conference.apitest E/rtc: #
>                                                                 # Fatal error in gen/sdk/android/generated_base_jni/jni/../../../../../../../third_party/webrtc/sdk/android/src/jni/jni_generator_helper.h, line 38
>                                                                 # last system error: 38
>                                                                 # Check failed: !env->ExceptionCheck()
>                                                                 # 
>                                                                 #
> 11-15 14:16:18.341 4396-4440/oms.test.conference.apitest A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4440 (signaling_threa)

**Comment by gopipeddisetti** [comment]
> 1: user1 join room
> 2: user1 publish local stream
> 3: user1 publication.stop()
> 
> repeat step 2 and step 3 for few times
> [publishStability.log](https://github.com/open-media-streamer/oms-client-android/files/2583878/publishStability.log)
> 
> > 11-15 14:16:18.331 4396-4440/oms.test.conference.apitest W/System.err: java.util.ConcurrentModificationException
> > 11-15 14:16:18.331 4396-4440/oms.test.conference.apitest W/System.err:     at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
> > 11-15 14:16:18.331 4396-4440/oms.test.conference.apitest W/System.err:     at oms.conference.ConferencePeerConnectionChannel.onSetSuccess(ConferencePeerConnectionChannel.java:103)
> > 11-15 14:16:18.331 4396-4440/oms.test.conference.apitest E/rtc: #
> > # Fatal error in gen/sdk/android/generated_base_jni/jni/../../../../../../../third_party/webrtc/sdk/android/src/jni/jni_generator_helper.h, line 38
> > # last system error: 38
> > # Check failed: !env->ExceptionCheck()
> > #
> > #
> > 11-15 14:16:18.341 4396-4440/oms.test.conference.apitest A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 4440 (signaling_threa)

Any solution for this, I am also facing this issue.
Any suggestion would be appreciated
Thank you.
