### ISSUE TITLE
conference : no frame send after publish local stream two hour later

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-android#83]
1: android connect server
2: adroid publish localstream with videoCodec h264 and resolution 1080p
3: android subscribe mix stream and this remote stream with h264
4: wait two hour

expect : android published video is good
actual : android send birtate =0 after publish two hour

android device : vivo x23
mcu version : mcu-all-bin-v20190315.tgz

**Comment by zhangyihui1** [comment]
also call publication.stop() lead crash after this issue:

W/OMXUtils: do not know color format 0x7f000789 = 2130708361
W/ExtendedACodec: Failed to get extension for extradata parameter
I/org.webrtc.Logging: EglRenderer: small_rendererDuration: 4006 ms. Frames received: 113. Dropped: 0. Rendered: 113. Render fps: 28.2. Average render time: 4928 μs. Average swapBuffer time: 3840 μs.
D/ACodec: dataspace changed to 0x10c10000 (R:2(Limited), P:3(BT601_6_625), M:3(BT601_6), T:3(SMPTE170M)) (R:2(Limited), S:1(BT709), T:3(SMPTE_170M))
I/org.webrtc.Logging: HardwareVideoEncoder: Config frame generated. Offset: 0. Size: 30
I/org.webrtc.Logging: HardwareVideoEncoder: Sync frame generated
    HardwareVideoEncoder: Prepending config frame of size 30 to output buffer with offset 0, size 15108
I/org.webrtc.Logging: CameraStatistics: Camera fps: 28.
I/SurfaceView: updateSystemUiVisibility, blackBackground = false, viewVisibility = 8, appBounds = Rect(0, 0 - 2256, 1080), mScreenRect = Rect(0, 114 - 480, 474), surface = org.webrtc.SurfaceViewRenderer{30abd48 G.E...... ......I. 0,0-480,360 #7f07006f app:id/small_renderer}
D/xxxxxxx: sendMsg: {"id":"625467159490509000"}
I/org.webrtc.Logging: CameraCapturer: Stop capture
    CameraCapturer: Stop capture: Nulling session
I/org.webrtc.Logging: CameraCapturer: Stop capture done
    CameraCapturer: dispose
    CameraCapturer: Stop capture
    CameraCapturer: Stop capture: No session open
    CameraCapturer: Stop capture done
I/org.webrtc.Logging: Camera1Session: Stop camera1 session on camera 1
    Camera1Session: Stop internal
    SurfaceTextureHelper: stopListening()
D/ICS: Wrong condition.
D/ICS: dalvik.system.VMStack.getThreadStackTrace(Native Method)
    java.lang.Thread.getStackTrace(Thread.java:1538)
    oms.base.CheckCondition.printStackTrace(CheckCondition.java:59)
    oms.base.CheckCondition.RCHECK(CheckCondition.java:41)
    oms.base.CheckCondition.DCHECK(CheckCondition.java:33)
    oms.conference.ConferenceClient.lambda$unpublish$33(ConferenceClient.java:286)
D/ICS: oms.conference.-$$Lambda$ConferenceClient$rXF2BrjhzhIrbI82Q-Jb9DWYbHY.call(Unknown Source:6)
    io.socket.client.Socket.onack(Socket.java:379)
    io.socket.client.Socket.onpacket(Socket.java:303)
    io.socket.client.Socket.access$100(Socket.java:24)
    io.socket.client.Socket$2$2.call(Socket.java:120)
    io.socket.emitter.Emitter.emit(Emitter.java:117)
    io.socket.client.Manager.ondecoded(Manager.java:427)
    io.socket.client.Manager.access$1600(Manager.java:30)
    io.socket.client.Manager$7.call(Manager.java:403)
    io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
    io.socket.client.Manager.ondata(Manager.java:419)
    io.socket.client.Manager.access$1000(Manager.java:30)
    io.socket.client.Manager$2.call(Manager.java:370)
    io.socket.emitter.Emitter.emit(Emitter.java:117)
    io.socket.engineio.client.Socket.onPacket(Socket.java:551)
    io.socket.engineio.client.Socket.access$1000(Socket.java:36)
    io.socket.engineio.client.Socket$5.call(Socket.java:335)
    io.socket.emitter.Emitter.emit(Emitter.java:117)
    io.socket.engineio.client.Transport.onPacket(Transport.java:126)
D/ICS: io.socket.engineio.client.Transport.onData(Transport.java:118)
    io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
    io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
    io.socket.thread.EventThread$2.run(EventThread.java:80)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
    java.lang.Thread.run(Thread.java:764)
E/EventThread: Task threw exception
    java.lang.RuntimeException: Wrong condition.
        at oms.base.CheckCondition.RCHECK(CheckCondition.java:42)
        at oms.base.CheckCondition.DCHECK(CheckCondition.java:33)
        at oms.conference.ConferenceClient.lambda$unpublish$33(ConferenceClient.java:286)
        at oms.conference.-$$Lambda$ConferenceClient$rXF2BrjhzhIrbI82Q-Jb9DWYbHY.call(Unknown Source:6)
        at io.socket.client.Socket.onack(Socket.java:379)
        at io.socket.client.Socket.onpacket(Socket.java:303)
        at io.socket.client.Socket.access$100(Socket.java:24)
        at io.socket.client.Socket$2$2.call(Socket.java:120)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.client.Manager.ondecoded(Manager.java:427)
        at io.socket.client.Manager.access$1600(Manager.java:30)
        at io.socket.client.Manager$7.call(Manager.java:403)
        at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
        at io.socket.client.Manager.ondata(Manager.java:419)
        at io.socket.client.Manager.access$1000(Manager.java:30)
        at io.socket.client.Manager$2.call(Manager.java:370)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
        at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
        at io.socket.engineio.client.Socket$5.call(Socket.java:335)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
        at io.socket.engineio.client.Transport.onData(Transport.java:118)
        at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
        at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
        at io.socket.thread.EventThread$2.run(EventThread.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime: FATAL EXCEPTION: EventThread
    Process: oms.sample.conference, PID: 25768
    java.lang.RuntimeException: Wrong condition.
        at oms.base.CheckCondition.RCHECK(CheckCondition.java:42)
        at oms.base.CheckCondition.DCHECK(CheckCondition.java:33)
        at oms.conference.ConferenceClient.lambda$unpublish$33(ConferenceClient.java:286)
        at oms.conference.-$$Lambda$ConferenceClient$rXF2BrjhzhIrbI82Q-Jb9DWYbHY.call(Unknown Source:6)
        at io.socket.client.Socket.onack(Socket.java:379)
        at io.socket.client.Socket.onpacket(Socket.java:303)
        at io.socket.client.Socket.access$100(Socket.java:24)
        at io.socket.client.Socket$2$2.call(Socket.java:120)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.client.Manager.ondecoded(Manager.java:427)
        at io.socket.client.Manager.access$1600(Manager.java:30)
        at io.socket.client.Manager$7.call(Manager.java:403)
        at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
        at io.socket.client.Manager.ondata(Manager.java:419)
        at io.socket.client.Manager.access$1000(Manager.java:30)
        at io.socket.client.Manager$2.call(Manager.java:370)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
        at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
        at io.socket.engineio.client.Socket$5.call(Socket.java:335)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
        at io.socket.engineio.client.Transport.onData(Transport.java:118)
        at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
        at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
        at io.socket.thread.EventThread$2.run(EventThread.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
V/Camera: sendReleaseCameraBroadCast isNormalCamera = true
Application terminated.

**Comment by zhangyihui1** [comment]
xiaomi 8 also found this issue
