### ISSUE TITLE
conference: subscription.stop() lead crash

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-client-android#92]
1: user1  and user2 join room
2 user1 publish local stream
3: user2 subscribe this remote stream
4: user1 publication.stop() this local stream and user2 wait remoteStream.onEnded event 
5: user2 call subscription.stop()

user2 crash log:
2019-03-26 22:28:58.793 7740-7845/owt.sample.conference E/AndroidRuntime: FATAL EXCEPTION: EventThread
    Process: owt.sample.conference, PID: 7740
    java.lang.RuntimeException: Wrong condition.
        at owt.base.CheckCondition.RCHECK(CheckCondition.java:42)
        at owt.base.CheckCondition.DCHECK(CheckCondition.java:33)
        at owt.conference.ConferenceClient.lambda$unsubscribe$35(ConferenceClient.java:401)
        at owt.conference.-$$Lambda$ConferenceClient$EIfrUEOOr5Z5IQrmt5Zu4FHy8Xw.call(Unknown Source:6)
        at io.socket.client.Socket.onack(Socket.java:379)
        at io.socket.client.Socket.onpacket(Socket.java:303)
        at io.socket.client.Socket.access$100(Socket.java:24)
        at io.socket.client.Socket$2$2.call(Socket.java:120)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.client.Manager.ondecoded(Manager.java:427)
        at io.socket.client.Manager.access$1600(Manager.java:30)
        at io.socket.client.Manager$7.call(Manager.java:403)
        at io.socket.parser.IOParser$Decoder.add(IOParser.java:105)
        at io.socket.client.Manager.ondata(Manager.java:419)
        at io.socket.client.Manager.access$1000(Manager.java:30)
        at io.socket.client.Manager$2.call(Manager.java:370)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Socket.onPacket(Socket.java:551)
        at io.socket.engineio.client.Socket.access$1000(Socket.java:36)
        at io.socket.engineio.client.Socket$5.call(Socket.java:335)
        at io.socket.emitter.Emitter.emit(Emitter.java:117)
        at io.socket.engineio.client.Transport.onPacket(Transport.java:126)
        at io.socket.engineio.client.Transport.onData(Transport.java:118)
        at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
        at io.socket.engineio.client.transports.WebSocket$1$2.run(WebSocket.java:71)
        at io.socket.thread.EventThread$2.run(EventThread.java:80)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by zhangyihui1** [comment]
android devices : xiaomi 8 
mcu version : 20190325 (software)
